# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=200)),
                ('subject', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('sources', models.TextField(default='')),
                ('date', models.DateField(default='')),
            ],
        ),
    ]
