# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_session_user'),
    ]

    operations = [
        
    ]
