# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_auto_20161216_1313'),
    ]

    operations = [
        
    ]
